version: '3.4'

services:
  balancesystem.api:
    image: ${DOCKER_REGISTRY-}balancesystemapi
    build:
      context: .
      dockerfile: BalanceApi/Dockerfile

  database:
    image: postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql_init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=passW0rd'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
