version: '3.4'

services:
  balancesystem.api:
    image: ${DOCKER_REGISTRY-}balancesystemapi
    build:
      context: .
      dockerfile: Balancesystem.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+
    ports:
      - 9000:80
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    restart: always
    container_name: pgsql_database
    volumes:
      - ../data:/var/lib/postgresql/data
      - ./postgresql_init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 3      
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=passW0rd'

  adminer:
    image: adminer
    restart: always
    container_name: adminer_helper
    ports:
      - 8080:8080 
